-- DEPRECATED / INTENTIONALLY EMPTY
--
-- This repository previously carried a dated production portfolio snapshot in
-- seed.sql. That is unsafe for source control and unsafe as an initialization
-- mechanism. Do NOT use this file to initialize or repair production.
--
-- Production holdings, trades, GTT state, cash/config values and other broker
-- or financial snapshots must be backed up outside GitHub using controlled D1
-- export / Time Travel procedures.
--
-- UC_MOMENTUM v1.1 schema changes are managed only through migrations/.
